Update qa-automation.yml

diff --git a/.github/workflows/qa-automation.yml b/.github/workflows/qa-automation.yml
--- a/.github/workflows/qa-automation.yml
+++ b/.github/workflows/qa-automation.yml
@@ -28,18 +28,24 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-      # creating reports folder
-      - name: Create report folder
-        run: mkdir -p reports
-      # Run Pytest
-      - name: Run Pytest Tests
-        run: |
-          pytest --html=reports/report.html
+          pip install allure-pytest
 
-      # Upload HTML report as GitHub Actions artifact
-      - name: Upload HTML Report
+    # Step 4: Run tests and generate Allure results
+      - name: Run Pytest
+        run: |
+          mkdir -p reports/allure-results
+          pytest --alluredir=reports/allure-results --capture=tee-sys || true
+        continue-on-error: true  # ensures workflow continues even if tests fail
+    
+      # Step 5: Generate Allure report
+      - name: Generate Allure Report
+        run: |
+          pip install allure-commandline
+          allure generate reports/allure-results -o reports/allure-report --clean || true
+    
+      # Step 6: Archive Allure report as artifact
+      - name: Upload Allure Report
         uses: actions/upload-artifact@v4
-        if: success() || failure()
         with:
-          name: pytest-html-report
-          path: reports
+          name: allure-report
+          path: reports/allure-report
